"""Vendor-neutral operational contracts for HEDP/SumiCore."""

from .execution import (
    AdapterExecutionResult,
    Authorization,
    ExecutionAuditEvent,
    ExecutionCapability,
    ExecutionCoordinator,
    ExecutionMode,
    ExecutionOutcome,
    ExecutionResult,
    GateDecision,
    OperationRegistry,
    function_port,
)
from .shadow_execution import (
    AuditEvent,
    CapabilityDescriptor,
    EvidenceQuality,
    GateResult,
    GateStatus,
    Intent,
    ShadowAssessment,
    ShadowExecutionGate,
    ShadowOperationRegistry,
    ShadowResult,
    StateEvidence,
)

__all__ = [
    "AdapterExecutionResult",
    "AuditEvent",
    "Authorization",
    "CapabilityDescriptor",
    "EvidenceQuality",
    "ExecutionAuditEvent",
    "ExecutionCapability",
    "ExecutionCoordinator",
    "ExecutionMode",
    "ExecutionOutcome",
    "ExecutionResult",
    "GateDecision",
    "GateResult",
    "GateStatus",
    "Intent",
    "OperationRegistry",
    "ShadowAssessment",
    "ShadowExecutionGate",
    "ShadowOperationRegistry",
    "ShadowResult",
    "StateEvidence",
    "function_port",
]
